<?php

namespace EcommerceBundle\Repository;

/**
 * panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPanierProduit($input){
        $em = $this->getEntityManager();
        $qb = $em
            ->createQuery("SELECT p
        FROM EcommerceBundle\Entity\Panier p
        WHERE p.produit =$input ");

        $results = $qb->getResult();
        return $results;
    }
}
