<?php

namespace EcommerceBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function produitparcategorie($id)
    {
        $em = $this->getEntityManager();
        $qb = $em
            ->createQuery("SELECT p
        FROM EcommerceBundle\Entity\Produit p
        WHERE p.categorie = :id")
            ->setParameter('id', $id);
        $results = $qb->getResult();
        return $results;


    }
}
