<?php

namespace EcommerceBundle\Repository;

/**
 * ProduitVenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitVenduRepository extends \Doctrine\ORM\EntityRepository
{
}
