<?php

namespace EcommerceBundle\Repository;

/**
 * wishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wishlistRepository extends \Doctrine\ORM\EntityRepository
{
 public function getWishlistByProduit($input)
 {

     $em = $this->getEntityManager();
     $qb = $em
         ->createQuery("SELECT p
        FROM EcommerceBundle\Entity\Wishlist p
        WHERE p.produit =$input ");

     $results = $qb->getResult();
     return $results;



 }

}
