<?php

namespace TGTBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CastingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CastingRepository extends EntityRepository
{
    public function RechercheTitreCasting($keyWord)
    {
        $query = $this->getEntityManager()->createQuery('SELECT v from TGTBundle:Casting v WHERE v.titreCasting LiKE :val')
            ->setParameter('val','%'.$keyWord.'%');

        return $query->getResult();

    }
}
