<?php

namespace TGTBundle\Repository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findallevents(){
        $qb = $this->createQueryBuilder('p')
            ->orderBy('p.dateEvents', 'ASC');
        $query = $qb->getQuery();

        return $query->execute();
    }
}
