<?php

namespace TGTBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{





    public function findBysimulation2($contenu1 ){

        $Query =$this->getEntityManager()->createQuery(

            " select a from TGTBundle:Question a where  a.contenu like :contenu1 ")

            ->setParameter('contenu1', '%'.$contenu1.'%' );

        return $Query->getResult();


    }

    public function findByafficheQ($mot){

        $Query =$this->getEntityManager()->createQuery(
            " select  a from TGTBundle:Question a  where a.Theme_id  = :id order by a.likeQuestion asc ")
            ->setParameter('id' ,$mot);
        return $Query->getResult();


    }




}
