<?php

namespace TGTBundle\Repository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByaffiche($mot){

        $Query =$this->getEntityManager()->createQuery(
            " select  a from TGTBundle:Reponse a where a.Question_id  = :id  order by a.likeReponce desc  ")
            ->setParameter('id' ,$mot);
        return $Query->getResult();


    }



    public function findBycalculerR($id){

        $Query =$this->getEntityManager()->createQuery(
            "select  COUNT (e) as e from TGTBundle:Reponse e WHERE e.Question_id = id" )

            ->setParameter('id',$id);

        return $result =$Query->getSingleScalarResult();
    }

}
