<?php

namespace FormationsBundle\Repository;

/**
 * CategorieFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
