<?php

namespace FormationsBundle\Repository;

/**
 * courRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class courRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySimulation($mot)
    {
        $Query=$this->getEntityManager()->createQuery(
            'select A from FormationsBundle:cour A where A.formations = :form_id')
            ->setParameter('form_id',$mot);
        return $Query->getResult();
    }

    public function calculerMoyenneRating()
    {

        $qb = $this->getEntityManager()
            ->createQuery('SELECT avg(f.ratingComm) 
                            FROM FormationsBundle:Commentaire f');

        return $qb->getSingleScalarResult();
    }
}

