<?php

namespace FormationsBundle\Repository;

/**
 * participerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participerRepository extends \Doctrine\ORM\EntityRepository
{
}
