<?php

namespace PublicationsBundle\Repository;

use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;

/**
 * CommentairePublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairePublicationRepository extends EntityRepository
{
    public function alterTable()
    {
        try {
            $query = $this->getEntityManager()->getConnection()->prepare("ALTER TABLE commentairePublication AUTO_INCREMENT = 1;")->execute();
        } catch (DBALException $e) {
            $message = $e->getMessage();
            echo "<script type='text/javascript'>alert('$message');</script>";
        }
    }

    public function calculRatingPub($id_pub)
    {
        $qb = $this->getEntityManager()
            ->createQuery('SELECT avg(f.ratingComm) 
                            FROM PublicationsBundle:CommentairePublication f
                            WHERE f.publication=:id
                            ')
            ->setParameter('id', $id_pub);
        return $qb->getResult();
    }

    public function trierParRating($id_pub)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT v from PublicationsBundle:CommentairePublication v WHERE v.publication=:id ORDER BY v.ratingComm DESC ')
            ->setParameter('id',$id_pub);
        return $query->getResult();
    }

    public function trierParDate($id_pub)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT v from PublicationsBundle:CommentairePublication v WHERE v.publication=:id ORDER BY v.dateComm DESC ')
            ->setParameter('id', $id_pub);
        return $query->getResult();
    }
}
