<?php

namespace PublicationsBundle\Repository;

use Doctrine\DBAL\DBALException;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use PublicationsBundle\Entity\CommentairePublication;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    public function alterTable()
    {
        try {
            $query = $this->getEntityManager()->getConnection()->prepare("ALTER TABLE Publication AUTO_INCREMENT = 1;")->execute();
        } catch (DBALException $e) {
            $message = $e->getMessage();
            //echo "<script type='text/javascript'>alert('$message');</script>";
            return new JsonResponse(['message' => $message], Response::HTTP_NOT_FOUND);
        }
    }

    public function updatePublication($id_pub){
        $rating = $this->getEntityManager()->getRepository(CommentairePublication::class)->calculRatingPub($id_pub);
        $qb = $this->getEntityManager()
            ->createQuery("UPDATE PublicationsBundle:Publication p
                           SET p.ratingPub=:rating
                           WHERE p.id_pub=:pub")
            ->setParameters(array('rating'=>$rating,'pub'=>$id_pub))
            ->execute();
    }
}
